In [1]:
import numpy as np

In [ ]:
# scaler arithmetic, normal python method.
arr = np.array([10,20,30,40])
print(arr + 10)
print(arr * 10)
print(arr ** 2)

[20 30 40 50]
[100 200 300 400]
[ 100  400  900 1600]


### vectorized math functions: 

numpy allows vectorized math functions, means-> operations are done on entire array at a same time.

In [5]:
radii = np.array([1,2,3])
print(np.pi * radii**2)

[ 3.14159265 12.56637061 28.27433388]


In [6]:
# Element wise arithmetic!
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2) #[5,7,9]

[5 7 9]


In [10]:
#comparison operators!

marks = np.array([55, 100, 69, 69, 10])
print(marks>=30)

[ True  True  True  True False]
