### BROADCASTING

It allows numpy to perform operations on arrays with different shapes by virtually expanding dimensions so,
they match the larger array's shape.

#### BroadCasting Rules

Arrays are compatible if:
1. Dimensions are same.
2. If one of the dimension is 1

If dimensions are different in size and neither is 1 then, broadcasting is not possible.(arrays -> not compatible.)


In [2]:
import numpy as np

In [2]:
a1 = np.array([[1,2,3,4]]) #(1X4)
print(a1.shape)

a2 = np.array([[1], [2], [3], [4]]) #(4X1)
print(a2.shape)

print(a1 * a2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [3]:
print(a1 + a2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [7]:
m1 = np.array([[2,4],[5,1]])
m2 = np.array([[4,2],[3,6]])
print(m1 + m2)

[[6 6]
 [8 7]]


In [4]:
#1 to 10 tables with the help of broadcasting

t1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
t2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(t1 * t2)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
