In [1]:
import numpy as np

### Filtering

Refers to the process of selecting elements from a given array according a specific condition.

In [4]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 69]])
teenageres = ages[ages<=18]
adults = ages[(ages>=18) & (ages<=65)]
print(teenageres)
print(adults)

[17 16 18 15 18]
[21 19 20 30 18 65 39 22 18 19 20]


In [ ]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 69]])
# where function syntax  -> where(condition, value_if_true, value_if_false)

adults = np.where(ages >= 18 , ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 69]]
